/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.CarCatalog;
import Model.CarCatalogHistory;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhavana
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
   
    CarCatalog ct;
    String ExpCer="";
    CarCatalogHistory history;
    public ViewJPanel(CarCatalog ct, CarCatalogHistory history) {
        initComponents();
        this.ct=ct;
        this.history=history;
        populateTable();
   
    }
    
    public void showData(){
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManagecars = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtSerialnumber = new javax.swing.JTextField();
        lblSerialnumber = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtManufactureyear = new javax.swing.JTextField();
        lblServicecustomer = new javax.swing.JLabel();
        txtServicecustomer = new javax.swing.JTextField();
        lblLastupdatedate = new javax.swing.JLabel();
        txtLastupdatedate = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        lblSeats = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        lblManufactureyear = new javax.swing.JLabel();
        lblExpiredcertificate = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Cars");

        tblManagecars.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblManagecars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial Number", "Brand", "Model", "Seats", "Status", "Manufacture Year", "Service Customer", "Last Updated Date", "Expired Maintenance", "City"
            }
        ));
        tblManagecars.setRowHeight(25);
        tblManagecars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblManagecarsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblManagecars);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("View/Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtSerialnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerialnumberKeyTyped(evt);
            }
        });

        lblSerialnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSerialnumber.setText("Serial Number");

        lblBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBrand.setText("Brand");

        lblModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblModel.setText("Model");

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        lblServicecustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblServicecustomer.setText("Service Customer");

        lblLastupdatedate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLastupdatedate.setText("Last Update Date");

        txtSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeatsKeyTyped(evt);
            }
        });

        lblSeats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSeats.setText("Seats");

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStatus.setText("Status");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Available", "Not Available" }));
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });

        lblManufactureyear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblManufactureyear.setText("Manufacture Year");

        lblExpiredcertificate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExpiredcertificate.setText("Expired Certificate");

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCity.setText("City");

        jRadioButton1.setText("YES");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("NO");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSerialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSerialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblServicecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManufactureyear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastupdatedate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExpiredcertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2))
                            .addComponent(txtManufactureyear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtServicecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastupdatedate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 137, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManufactureyear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufactureyear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServicecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServicecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastupdatedate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastupdatedate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(lblExpiredcertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
//         df.addRow(cp.data);

        String serialNumber = txtSerialnumber.getText() ;
        String carManufacturername  =  txtBrand.getText();
        String modelNumber = txtModel.getText();
        //numberofSeats = Integer.parseInt(txtSeats.getText());
        String numberofSeats  = txtSeats.getText();
        String Status =  comboStatus.getSelectedItem().toString();
        String manufactureYear= txtManufactureyear.getText();
        String serviceCustomer    =  txtServicecustomer.getText(); //String
        String LastUpdated   = txtLastupdatedate.getText(); //String
        String expiredMaintenance =jRadioButton1.getText();
        String City = txtCity.getText();
        
        for(CarCatalog carCatalog :  history.getHistory()){
            boolean isFiltered = true;
            if(isFiltered && 
                    !carManufacturername.equalsIgnoreCase(carCatalog.getCarManufacturername()) && 
                    !carManufacturername.isEmpty()){
                isFiltered = false;
                carCatalog.setIsFiltered(isFiltered);
                continue;
            }
            
            if(isFiltered && 
                    !modelNumber.equalsIgnoreCase(carCatalog.getModelNumber()) && 
                    !modelNumber.isEmpty()){
                isFiltered = false;
                carCatalog.setIsFiltered(isFiltered);
                continue;
            }
            
            if(isFiltered && 
                    !manufactureYear.equalsIgnoreCase(carCatalog.getManufactureYear()) && 
                    !manufactureYear.isEmpty()){
                isFiltered = false;
                carCatalog.setIsFiltered(isFiltered);
                continue;
            }
            
            if(isFiltered && 
                    !serviceCustomer.equalsIgnoreCase(carCatalog.getServiceCustomer()) && 
                    !serviceCustomer.isEmpty()){
                isFiltered = false;
                carCatalog.setIsFiltered(isFiltered);
                continue;
            }
             if(isFiltered && 
                    !LastUpdated.equalsIgnoreCase(carCatalog.getLastUpdated()) && 
                    !LastUpdated.isEmpty()){
                isFiltered = false;
                carCatalog.setIsFiltered(isFiltered);
                continue;
            }
             if(isFiltered && 
                    !City.equalsIgnoreCase(carCatalog.getCity()) && 
                    !City.isEmpty()){
                isFiltered = false;
                carCatalog.setIsFiltered(isFiltered);
                continue;
            }
            
            carCatalog.setIsFiltered(isFiltered);
        }
        this.populateTable();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        DefaultTableModel model = (DefaultTableModel) tblManagecars.getModel();
        if (tblManagecars.getSelectedRowCount() == 1)
        {
        String Serialnumber = txtSerialnumber.getText();
        String Brand = txtBrand.getText();
        String Model = txtModel.getText();
        String Seats  = txtSeats.getText();
        String comboStatusString = comboStatus.getSelectedItem().toString();
       
        String Manufactureyear = txtManufactureyear.getText();
        String Servicecustomer = txtServicecustomer.getText();
        String Lastupdatedate = new SimpleDateFormat("MM/dd/yyyy").format(new Date());
        //setText(tblExpiredcertificate);
        String ExpiredCertificate= (jRadioButton1.isSelected()) ? "Yes" : "No";
        String City = txtCity.getText(); 
  
        
        model.setValueAt(Serialnumber, tblManagecars.getSelectedRow(),0);
        model.setValueAt(Brand, tblManagecars.getSelectedRow(),1);
        model.setValueAt(Model, tblManagecars.getSelectedRow(),2);
        model.setValueAt(Seats, tblManagecars.getSelectedRow(),3);
        // model.setValueAt();
                model.setValueAt(comboStatusString, tblManagecars.getSelectedRow(),4);
        model.setValueAt(Manufactureyear, tblManagecars.getSelectedRow(),5);
        model.setValueAt(Servicecustomer, tblManagecars.getSelectedRow(),6);
        model.setValueAt(Lastupdatedate, tblManagecars.getSelectedRow(),7);
        model.setValueAt(ExpiredCertificate,tblManagecars.getSelectedRow(),8);
        // model.setValueAt();
        model.setValueAt(City, tblManagecars.getSelectedRow(),9);
      
        
        JOptionPane.showMessageDialog(this,"Updated Sucessfully");
        }
        else {
            if (model.getRowCount() == 0)
            {
                JOptionPane.showMessageDialog(this,"The table is empty");
            }
            else {
                JOptionPane.showMessageDialog(this,"Please select single row for update");
            }
        }
        
        
        
       // int selectedRowIndex = tblManagecars.getSelectedRow();
       // if (selectedRowIndex <0)
       // {
        //    JOptionPane.showMessageDialog(this,"Please select a row to update");
        //    return;
        //}
        
       
       //CarCatalog selectedcar = (CarCatalog) model.getValueAt(selectedRowIndex,0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        //ExpiredCertificate =jButton1.getName();s
        ExpCer=jRadioButton2.getName(); 
        
       
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
ExpCer=jRadioButton2.getName();        // TODO add your handling code here:
       // jButton1.getSelectedIcon();
        

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void tblManagecarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblManagecarsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel) tblManagecars.getModel();
        String tblSerialnumber = tblmodel.getValueAt(tblManagecars.getSelectedRow(),0).toString();
        String tblBrand = tblmodel.getValueAt(tblManagecars.getSelectedRow(),1).toString();
        String tblModel = tblmodel.getValueAt(tblManagecars.getSelectedRow(),2).toString();
        String tblSeats = tblmodel.getValueAt(tblManagecars.getSelectedRow(),3).toString();
        String tblStatus = tblmodel.getValueAt(tblManagecars.getSelectedRow(),4).toString();
        String tblManufactureyear = tblmodel.getValueAt(tblManagecars.getSelectedRow(),5).toString();
        String tblServicecustomer = tblmodel.getValueAt(tblManagecars.getSelectedRow(),6).toString();
        String tblLastupdatedate = tblmodel.getValueAt(tblManagecars.getSelectedRow(),7).toString();
        String tblExpiredcertificate = tblmodel.getValueAt(tblManagecars.getSelectedRow(),8).toString();
        String tblCity = tblmodel.getValueAt(tblManagecars.getSelectedRow(),9).toString();
        
        
        txtSerialnumber.setText(tblSerialnumber);
        txtBrand.setText(tblBrand);
        txtModel.setText(tblModel);
        txtSeats.setText(tblSeats);
        //jButton1.setSelected(true);
        
        //comboStatus.setText(tblStatus);
        txtManufactureyear.setText(tblManufactureyear);
        txtServicecustomer.setText(tblServicecustomer);
        txtLastupdatedate.setText(tblLastupdatedate);
        //setText(tblExpiredcertificate);
        txtCity.setText(tblCity);
        
        if(tblExpiredcertificate.equalsIgnoreCase("yes")) jRadioButton1.setSelected(true);
        else jRadioButton2.setSelected(true);
        
        comboStatus.setSelectedIndex((tblStatus.equalsIgnoreCase("Available")?1:2));
    }//GEN-LAST:event_tblManagecarsMouseClicked

    private void txtSerialnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialnumberKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();}
    }//GEN-LAST:event_txtSerialnumberKeyTyped

    private void txtSeatsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeatsKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();}
        
    }//GEN-LAST:event_txtSeatsKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblExpiredcertificate;
    private javax.swing.JLabel lblLastupdatedate;
    private javax.swing.JLabel lblManufactureyear;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialnumber;
    private javax.swing.JLabel lblServicecustomer;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblManagecars;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtLastupdatedate;
    private javax.swing.JTextField txtManufactureyear;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialnumber;
    private javax.swing.JTextField txtServicecustomer;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel)tblManagecars.getModel();
        model.setRowCount(0);
         for(CarCatalog cd: history.getHistory())
         {
             if (!cd.IsFiltered()) continue ;
            Object o[]=new Object[10];
            
         o[0] = cd.getSerialNumber();
         o[1] = cd.getCarManufacturername();
         o[2]=cd.getModelNumber(); 
         o[3] = cd.getNumberofSeats();
         o[4]=cd.getStatus();
           o[5]=cd.getManufactureYear();
           o[6]=cd.getServiceCustomer();
           o[7]=cd.getLastUpdated();
           o[8]=cd.getExpiredMaintenance();
           o[9]=cd.getCity();
         
         model.addRow(o);
         }
    }
}
